USE [master]
GO
CREATE LOGIN [StoreMan] WITH PASSWORD=N'StoreMan1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [MiRas]
GO
CREATE USER [StoreMan] FOR LOGIN [StoreMan]
GO
USE [MiRas]
GO
ALTER ROLE [StoreMan_role] ADD MEMBER [StoreMan]
GO
