USE [master]
GO
CREATE LOGIN [Client] WITH PASSWORD=N'Client1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [MiRas]
GO
CREATE USER [Client] FOR LOGIN [Client]
GO
USE [MiRas]
GO
ALTER ROLE [Client_role] ADD MEMBER [Client]
GO
